services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_DB: insertokname_db
        POSTGRES_USER: insertokname
        POSTGRES_PASSWORD: DebugPassword
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ~/apps/postgres:/var/lib/postgresql/data
      ports:
        - 5432:5432