services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_DB: insertokname_db
        POSTGRES_USER: insertokname
        POSTGRES_PASSWORD: DebugPassword
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ~/.BackendOlimpiadaIsto/postgres:/var/lib/postgresql/data
      ports:
        - 5432:5432
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8888
      - DB_HOST=db
    ports:
      - "8888:8888"
    depends_on:
      - db