// <auto-generated />
using System;
using System.Collections.Generic;
using BackendBaseTemplate.infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendBaseTemplate.domain.Entities.EntityTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EntityTemplates");
                });

            modelBuilder.Entity("BackendBaseTemplate.domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendBaseTemplate.domain.Entities.EntityTemplate", b =>
                {
                    b.OwnsOne("BackendBaseTemplate.domain.Commands.DataTransferObjects.EntityTemplateDataObject", "EntityTemplateDataObjects", b1 =>
                        {
                            b1.Property<Guid>("EntityTemplateId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<DateTime>>("TemplateData")
                                .IsRequired()
                                .HasColumnType("timestamp with time zone[]");

                            b1.HasKey("EntityTemplateId");

                            b1.ToTable("EntityTemplates");

                            b1.WithOwner()
                                .HasForeignKey("EntityTemplateId");
                        });

                    b.Navigation("EntityTemplateDataObjects")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
